name: ${APP_NAME}
services:
  nginx-php:
    build:
        context: ./nginx-php
        dockerfile: Dockerfile
        args:
         - APP_NAME=${APP_NAME}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_USER=${POSTGRES_USER}

    ports:
      - 5500:80
      - 5543:443
    volumes:
      - ./src:/var/www/html
      - ./cert:/etc/nginx/ssl
    entrypoint: ['/start.sh']
  postgresql:
    image: postgres:13.21-alpine3.20
    restart: on-failure
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
networks:
  nginx-postgresql-laravel: {}
